[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd functions && npm ci"]

[phases.build]
cmds = ["cd functions && npm run build"]

[start]
cmd = "cd functions && npx prisma migrate deploy && node src/index.js"
